### PR TITLE
added .install recipe for Visual Studio Code

### PR DESCRIPTION
**Pull request by discentem**
Please provide feedback if I have done anything silly in the code or if there are logical improvements to be made. This is one of the first recipes I've written. 

The recipe does what I expect: installs (copies) the `.app` to `/Applications/Visual Code Studio.app`.

### CODE REVIEW

**Comment by fonteijnf** [comment]
Hi Brandon,

thank you for your request. I'm not a great recipe maker myself so don't worry.
I tested the recipe, which works fine if you don't have Visual Studio Code already installed. But it fails when you already have one (probably of the same version) installed in your /Applications.

I can fix it for you, but if you prefer making the fix yourself, please do!

A tiny edit in description, replacing vfuse with Visual Studio Code would be nice and
for the installing part I suggest using Unarchiver > DmgCreator > InstallFromDMG (in that order).

kind regards,
Frank

**Comment by discentem** [comment]
I've just fixed the description, sorry about that. I did a bit of copy and pasting from other recipes and forgot to change it. 

Is there are reason I shouldn't piggy back off the `.download` recipe, where the app is already unarchived? My recipe uses that as a parent.

**Comment by discentem** [comment]
I ended up just using https://github.com/BaddMann/autopkg-Recipes/tree/master/VSCode

**Comment by fonteijnf** [comment]
"Is there are reason I shouldn't piggy back off the .download recipe, where the app is already unarchived? My recipe uses that as a parent."
-- Fair point. It is indeed unnecessary! See, I'm no recipe hero 👎 

I will close the pull request since I gather you will be using BaddMann's recipe now.
BaddMann to the rescue ;)

kind regards,
Frank

**Pull request closed without merging**
